---
openapi: 3.0.3
info:
  title: Catalog Management API Documentation
  version: 1.0.0
servers: []
paths:
  "/auth/login":
    post:
      summary: create
      tags:
      - Devise::Session
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                owner:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                  required:
                  - email
                  - password
              required:
              - owner
            example:
              owner:
                email: owner1@example.com
                password: password123
      responses:
        '201':
          description: returns JWT token and 201 code
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  email:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
                  name:
                    type: string
                required:
                - id
                - email
                - created_at
                - updated_at
                - name
              example:
                id: 3
                email: owner1@example.com
                created_at: '2025-07-27T18:22:57.511Z'
                updated_at: '2025-07-27T18:22:57.529Z'
                name: Owner 1
  "/auth/logout":
    delete:
      summary: destroy
      tags:
      - Devise::Session
      security:
      - BearerToken: []
      responses:
        '204':
          description: invalidate token and returns 204
  "/auth/signup":
    post:
      summary: create
      tags:
      - Devise::Registration
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                owner:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                    name:
                      type: string
                  required:
                  - email
                  - password
                  - name
              required:
              - owner
            example:
              owner:
                email: new.owner@email.com
                password: password123
                name: New Owner
      responses:
        '201':
          description: renders a JSON response with the new owner
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  email:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
                  name:
                    type: string
                required:
                - id
                - email
                - created_at
                - updated_at
                - name
              example:
                id: 2
                email: new.owner@email.com
                created_at: '2025-07-27T18:22:57.479Z'
                updated_at: '2025-07-27T18:22:57.479Z'
                name: New Owner
        '422':
          description: renders a JSON response with errors for the new owner
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    properties:
                      name:
                        type: array
                        items:
                          type: string
                      email:
                        type: array
                        items:
                          type: string
                      password:
                        type: array
                        items:
                          type: string
                    required:
                    - name
                required:
                - errors
              example:
                errors:
                  name:
                  - can't be blank
                  email:
                  - can't be blank
                  password:
                  - can't be blank
  "/catalog/{owner_id}":
    get:
      summary: show
      tags:
      - Catalog
      security:
      - JWT: []
      parameters:
      - name: owner_id
        in: path
        required: true
        schema:
          type: integer
        example: 7
      responses:
        '200':
          description: renders a successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  catalog_url:
                    type: string
              example:
                catalog_url: https://catalog-management-api-b.s3.us-east-1.amazonaws.com/7-catalog.json
  "/categories":
    get:
      summary: index
      tags:
      - Category
      security:
      - BearerToken: []
      responses:
        '200':
          description: renders a successful response
          content:
            application/json:
              schema:
                type: array
                items: {}
              example: []
    post:
      summary: create
      tags:
      - Category
      security:
      - BearerToken: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                category:
                  type: object
                  properties:
                    title:
                      type: string
                    description:
                      type: string
                  required:
                  - title
                  - description
              required:
              - category
            example:
              category:
                title: My category
                description: My text
      responses:
        '201':
          description: renders a JSON response with the new category
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  owner_id:
                    type: integer
                  title:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
                  description:
                    type: string
                required:
                - id
                - owner_id
                - title
                - created_at
                - updated_at
                - description
              example:
                id: 3
                owner_id: 8
                title: My category
                created_at: '2025-07-27T18:22:57.828Z'
                updated_at: '2025-07-27T18:22:57.828Z'
                description: My text
        '422':
          description: renders a JSON response with errors for the new category
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: array
                    items:
                      type: string
                required:
                - title
              example:
                title:
                - can't be blank
  "/categories/{id}":
    delete:
      summary: destroy
      tags:
      - Category
      security:
      - BearerToken: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        example: 7
      responses:
        '204':
          description: destroys the requested category
    get:
      summary: show
      tags:
      - Category
      security:
      - BearerToken: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        example: 1
      responses:
        '200':
          description: renders a successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  owner_id:
                    type: integer
                  title:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
                  description:
                    type: string
                required:
                - id
                - owner_id
                - title
                - created_at
                - updated_at
                - description
              example:
                id: 1
                owner_id: 8
                title: My category
                created_at: '2025-07-27T18:22:57.777Z'
                updated_at: '2025-07-27T18:22:57.777Z'
                description: My text
    patch:
      summary: update
      tags:
      - Category
      security:
      - BearerToken: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        example: 6
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                category:
                  type: object
                  properties:
                    description:
                      type: string
                  required:
                  - description
              required:
              - category
            example:
              category:
                description: My simple description
      responses:
        '200':
          description: renders a JSON response with the category
          content:
            application/json:
              schema:
                type: object
                properties:
                  owner_id:
                    type: integer
                  description:
                    type: string
                  id:
                    type: integer
                  title:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
                required:
                - owner_id
                - description
                - id
                - title
                - created_at
                - updated_at
              example:
                owner_id: 8
                description: My simple description
                id: 5
                title: My category
                created_at: '2025-07-27T18:22:57.879Z'
                updated_at: '2025-07-27T18:22:57.889Z'
        '422':
          description: renders a JSON response with errors for the category
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: array
                    items:
                      type: string
                required:
                - title
              example:
                title:
                - can't be blank
  "/products":
    get:
      summary: index
      tags:
      - Product
      security:
      - BearerToken: []
      responses:
        '200':
          description: renders a successful response
          content:
            application/json:
              schema:
                type: array
                items: {}
              example: []
    post:
      summary: create
      tags:
      - Product
      security:
      - BearerToken: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                price:
                  type: number
                  format: float
                category_id:
                  type: integer
              required:
              - title
              - description
              - price
              - category_id
            example:
              title: My product
              description: My text
              price: 9.99
              category_id: 8
      responses:
        '201':
          description: renders a JSON response with the new product
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  description:
                    type: string
                  price:
                    type: string
                  category_id:
                    type: integer
                  created_at:
                    type: string
                  updated_at:
                    type: string
                required:
                - id
                - title
                - description
                - price
                - category_id
                - created_at
                - updated_at
              example:
                id: 3
                title: My product
                description: My text
                price: '9.99'
                category_id: 8
                created_at: '2025-07-27T18:22:58.044Z'
                updated_at: '2025-07-27T18:22:58.044Z'
        '422':
          description: renders a JSON response with errors for the new product
          content:
            application/json:
              schema:
                type: object
                properties:
                  price:
                    type: array
                    items:
                      type: string
                required:
                - price
              example:
                price:
                - must be greater than 0
  "/products/{id}":
    delete:
      summary: destroy
      tags:
      - Product
      security:
      - BearerToken: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        example: 7
      responses:
        '204':
          description: destroys the requested product
    get:
      summary: show
      tags:
      - Product
      security:
      - BearerToken: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        example: 1
      responses:
        '200':
          description: renders a successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  description:
                    type: string
                  price:
                    type: string
                  category_id:
                    type: integer
                  created_at:
                    type: string
                  updated_at:
                    type: string
                required:
                - id
                - title
                - description
                - price
                - category_id
                - created_at
                - updated_at
              example:
                id: 1
                title: My product
                description: My text
                price: '9.99'
                category_id: 8
                created_at: '2025-07-27T18:22:57.994Z'
                updated_at: '2025-07-27T18:22:57.994Z'
    patch:
      summary: update
      tags:
      - Product
      security:
      - BearerToken: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        example: 6
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                price:
                  type: number
                  format: float
              required:
              - price
            example:
              price: 909.9
      responses:
        '200':
          description: renders a JSON response with the product
          content:
            application/json:
              schema:
                type: object
                properties:
                  price:
                    type: string
                  category_id:
                    type: integer
                  id:
                    type: integer
                  title:
                    type: string
                  description:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
                required:
                - price
                - category_id
                - id
                - title
                - description
                - created_at
                - updated_at
              example:
                price: '909.9'
                category_id: 8
                id: 5
                title: My product
                description: My text
                created_at: '2025-07-27T18:22:58.102Z'
                updated_at: '2025-07-27T18:22:58.112Z'
        '422':
          description: renders a JSON response with errors for the product
          content:
            application/json:
              schema:
                type: object
                properties:
                  price:
                    type: array
                    items:
                      type: string
                required:
                - price
              example:
                price:
                - must be greater than 0
  "/up":
    get:
      summary: show
      tags:
      - Rails::Health
      responses:
        '200':
          description: returns 200 with valid token
          content:
            text/html:
              schema:
                type: string
              example: '<!DOCTYPE html><html><body style="background-color: green"></body></html>'
components:
  securitySchemes:
    BearerToken:
      description: Authenticate API requests via a JWT
      type: http
      scheme: bearer
      bearerFormat: JWT
